.github/workflows/test.yml
package.json

feat() Change name to gherkin-lint-ng

feat() Add tests

---

.eslintrc.json
changelog/no-unused-variables-spaces.md
src/rules/no-unused-variables.js
test/rules/no-unused-variables/NoViolations.feature

feat() Improve `no-unused-variables` to handle spaces on usage.

---

.editorconfig
changelog/formatter-improve.md
src/formatters/json.js
src/formatters/stylish.js
src/formatters/xunit.js
src/index.js

- xunit: Wrap with testsuites object and add count attribute
- stylish: Add error count to final output
Closes #11

feat() Improve formatters

---

README.md
changelog/table-align.md
src/rules/table-align.js
test/rules/all-rules/all-rules.js
test/rules/table-align/aligned.feature
test/rules/table-align/crazy-spaces.feature
test/rules/table-align/no-spaces.feature
test/rules/table-align/simple-config.feature
test/rules/table-align/table-align.js

feat() Support table alignment rule

---

README.md
changelog/max-tags-lines.md
src/rules/max-tags-lines.js
test/rules/max-tags-lines/max-tags-lines.js
test/rules/max-tags-lines/tagged.feature
test/rules/max-tags-lines/untagged.feature

feat() Support max tags lines rule

---

README.md
changelog/required-tags.md
src/rules/required-tags.js
test/rules/required-tags/NoViolations.feature
test/rules/required-tags/Violations.feature
test/rules/required-tags/required-tags.js

feat(rules) Allow subset array to include optional required tags.

---

src/rules/required-tags.js
test/rules/required-tags/deprecated/required-tags.js
test/rules/required-tags/required-tags.js

feat(rules) Improve `required-tags` message

---

README.md
src/rules/indentation.js
test/rules/indentation/CorrectIndentationSpaces.feature
test/rules/indentation/CorrectIndentationTabs.feature
test/rules/indentation/CorrectIndentationWithFeatureAndScenarioAndExamplesOverrides.feature
test/rules/indentation/CorrectIndentationWithScenarioAndExamplesTagOverrides.feature
test/rules/indentation/WrongIndentationDifferentLanguage.feature
test/rules/indentation/WrongIndentationSpaces.feature
test/rules/indentation/WrongIndentationTabs.feature
test/rules/indentation/indentation.js

feat(rules) Improve `indentation` to support `examples tag`

---

changelog/required-tags-global-fix.md
src/rules/no-dupe-scenario-names.js
src/rules/required-tags.js
src/rules/utils/gherkin.js
test/rules/required-tags/NoViolations.feature
test/rules/required-tags/NoViolationsFullTagged.feature
test/rules/required-tags/ViolationsFullTagged.feature
test/rules/required-tags/required-tags.js

feat(utils/gherkin) Created method `getNodeForPickle` to map nodes and pickles
Fixes #68

feat(rules) Fix and improve `required-tags` using global

---

package.json

* Re-sort some properties
* Add fundings links
* Add homepage and bugs links

feat(package.json) package.json tweaks

---

.nycrc
.travis.yml
README.md
babel.config.js
changelog/related-tags.md
package.json
src/rules/related-tags.js
test/rules/related-tags/NoViolations.feature
test/rules/related-tags/Violations.feature
test/rules/related-tags/related-tags.js

feat(rules) Added rule `related-tags`.
chore(babel|nyc) Babel/nyc tweaks.

feat(rules) Added rule `related-tags`.

---

src/rules/table-align.ts
test/rules/table-align/escape.feature
test/rules/table-align/table-align.ts
tsconfig.json

continue work started in https://github.com/Nyaran/gplint/pull/357
turned out we need to add slashes back for mis-align detection to work properly

Escape pipes

---

.github/workflows/test.yml

Revert "chore(deps): bump codecov/codecov-action from 3 to 4"

---

package.json

This is a new release v2.0.0-alpha.1

Release v2.0.0-alpha.1

---

package.json

This is a new release v2.0.0-alpha.2

Release v2.0.0-alpha.2

---

package.json

This is a new release v2.0.0-alpha.3

Release v2.0.0-alpha.3

---

package.json

This is a new release v2.0.0-alpha.4

Release v2.0.0-alpha.4

---

package.json

This is a new release v2.0.0-alpha.5

Release v2.0.0-alpha.5

---

package.json

This is a new release v2.0.0-beta.0

Release v2.0.0-beta.0

---

package.json

This is a new release v2.0.0-beta.1

Release v2.0.0-beta.1

---

package.json

This is a new release v2.0.0-beta.2

Release v2.0.0-beta.2

---

package.json

This is a new release v2.0.0-beta.3

Release v2.0.0-beta.3

---

package.json

This is a new release v2.0.0-beta.4

Release v2.0.0-beta.4

---

package.json

This is a new release v2.0.0-beta.5

Release v2.0.0-beta.5

---

.github/workflows/create-gh-release.yml

https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/

chore: Update to avoid set-output deprecation

---

package.json

This is a new release v2.0.0-beta.6

Release v2.0.0-beta.6

---

package.json

This is a new release v2.2.0-rc.0

Release v2.2.0-rc.0

---

package.json

This is a new release v2.2.0-rc.1

Release v2.2.0-rc.1

---

src/rules/max-keywords.ts
test/rules/max-keywords/NoViolations.feature
test/rules/max-keywords/Violations.feature
test/rules/max-keywords/max-keywords.ts

Closes #790
```json5
{
"max-keyword": {
"when": 1, // Limited to 1
"given": 0, // Means "Given" is forbidden
"then": -1: // Means unlimited
}
}
```

Add `max-keywords` rule

---

package.json

This is a new release v2.3.0-beta.0

Release v2.3.0-beta.0

---

src/rules/max-keywords.ts

chore: Fix typo

---

src/rules/max-keywords.ts
test/rules/max-keywords/Violations.feature
test/rules/max-keywords/max-keywords.ts

Add `ignoreConjunctions` to `max-keywords` rule.

---

package.json

This is a new release v2.3.0-beta.1

Release v2.3.0-beta.1

---

package.json

This is a new release v2.3.1-beta.0

Release v2.3.1-beta.0

---

package.json

This is a new release v2.4.0-beta.0

Release v2.4.0-beta.0
